### PR TITLE
Fixed some bugs

### PR DESCRIPTION
**Pull request by andot**
Fixed DivideByZeroException.
Changed Get-WmiObject calls to Get-CimInstance calls.
Append whitespaces before System Specs.
Replace aliases with their cmdlets.

### CODE REVIEW

**Comment by JulianChow94** [comment]
If you resolve the conflicts I can merge this in.

**Comment by lucknaumann** [comment]
Hi @JulianChow94 & @andot 
Thanks for fixing and merging! 
This fixed a weird error I was getting: `Resolution: System.Object[] x System.Object[] (System.Object[]Hz)`

FYI - I am still getting errors relating to DivideByZeroException and Append whitespaces before System Specs. And a **new** error related to the CD/DVD drive (D:) where the percentage is wrong as it's empty. It used to display correctly.

Attempted to divide by zero.
At C:\Program Files\WindowsPowerShell\Modules\windows-screenfetch\1.0.2\Data.psm1:174 char:13
+             $FreeDiskPercent = ($FreeDiskSizeGB / $DiskSizeGB) * 100;
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

Attempted to divide by zero.
At C:\Program Files\WindowsPowerShell\Modules\windows-screenfetch\1.0.2\Data.psm1:178 char:13
+             $UsedDiskPercent = ($UsedDiskSizeGB / $DiskSizeGB) * 100;
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

Screenfetch : System Specs occupies more lines than the Ascii Art resource selected
At line:1 char:1
+ Screenfetch
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Screenfetch

me@machinename
OS: Microsoft Windows 10 Home 64-bit
Kernel: 10.0.17763
Uptime: 3d 5h 25m 22s
Motherboard: Alienware 068R5X
Shell: PowerShell 5.1.17763.1007
Resolution: 1920 x 1080
Window Manager: DWM
Font: Segoe UI
CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
GPU NVIDIA GeForce GTX 770M
RAM: 5354MB / 16269 MB (33%)
Disk C: 380GB / 494GB (77%)
Disk D: 0GB / 0GB (77%)
Disk E: 142GB / 194GB (73%)
Disk F: 1228GB / 1,863GB (66%)
Disk G: 3640GB / 3,726GB (98%)

**Comment by JulianChow94** [comment]
Hey @lucknaumann thanks for pointing this out, I will look into this.

**Comment by lucknaumann** [comment]
@JulianChow94 
Yes. I ran Update-Module -Name windows-screenfetch and also just Update-Module to be certain. Unless I should do something else?

**Comment by lucknaumann** [comment]
@JulianChow94 & @andot
I deleted my other post because I was mistaken about my methods. Also, I didn't launch a new instance of PS so the changes weren't entirely in effect. 

I cloned the repo, opened PS there, then ran `Import-Module –Name C:\theDirectory\windows-screenfetch.psm1 -Verbose`.

I had to replace the psd1 file with the old one as it's now empty and won't run as a module. After replacement, it now runs without error messages and the empty CD/DVD drive displays the correct information. **_However_,** the changes to the display in the 'Data.psm1' file now gives me the odd `Resolution: System.Object[] x System.Object[] (System.Object[]Hz)` whereas the old version gave me the actual correct values. So, I removed the changes to the `Function Get-Displays()` section and _voila!_ It works perfectly now!

**Pull request merged**
